In [1]:
from utils import Preprocessing

In [2]:
prep = Preprocessing('fer2013')

In [3]:
prep.load_data('fer2013.csv', name='alldata')

       emotion                                             pixels        Usage
0            0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...     Training
1            0  151 150 147 155 148 133 111 140 170 174 182 15...     Training
2            2  231 212 156 164 174 138 161 173 182 200 106 38...     Training
3            4  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...     Training
4            6  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...     Training
5            2  55 55 55 55 55 54 60 68 54 85 151 163 170 179 ...     Training
6            4  20 17 19 21 25 38 42 42 46 54 56 62 63 66 82 1...     Training
7            3  77 78 79 79 78 75 60 55 47 48 58 73 77 79 57 5...     Training
8            3  85 84 90 121 101 102 133 153 153 169 177 189 1...     Training
9            2  255 254 255 254 254 179 122 107 95 124 149 150...     Training
10           0  30 24 21 23 25 25 49 67 84 103 120 125 130 139...     Training
11           6  39 75 78 58 58 45 49 48 103 156 81 45 41 38 49...     Training
12           6  219 213 206 202 209 217 216 215 219 218 223 23...     Training
13           6  148 144 130 129 119 122 129 131 139 153 140 12...     Training
14           3  4 2 13 41 56 62 67 87 95 62 65 70 80 107 127 1...     Training
15           5  107 107 109 109 109 109 110 101 123 140 144 14...     Training
16           3  14 14 18 28 27 22 21 30 42 61 77 86 88 95 100 ...     Training
17           2  255 255 255 255 255 255 255 255 255 255 255 25...     Training
18           6  134 124 167 180 197 194 203 210 204 203 209 20...     Training
19           4  219 192 179 148 208 254 192 98 121 103 145 185...     Training
20           4  1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 7 12 23 45 38 ...     Training
21           2  174 51 37 37 38 41 22 25 22 24 35 51 70 83 98 ...     Training
22           0  123 125 124 142 209 226 234 236 231 232 235 22...     Training
23           0  8 9 14 21 26 32 37 46 52 62 72 70 71 73 76 83 ...     Training
24           3  252 250 246 229 182 140 98 72 53 44 67 95 95 8...     Training
25           3  224 227 219 217 215 210 187 177 189 200 206 21...     Training
26           5  162 200 187 180 197 198 196 192 176 152 136 11...     Training
27           0  236 230 225 226 228 209 199 193 196 211 199 19...     Training
28           3  210 210 210 210 211 207 147 103 68 60 47 70 12...     Training
29           5  50 44 74 141 187 187 169 113 80 128 181 172 76...     Training
...        ...                                                ...          ...
35857        5  253 255 229 150 89 61 54 60 55 49 61 50 56 45 ...  PrivateTest
35858        4  11 11 11 13 20 27 38 41 38 34 20 13 10 39 85 1...  PrivateTest
35859        4  11 13 16 27 24 26 89 161 190 197 201 206 210 2...  PrivateTest
35860        3  27 42 62 91 112 118 122 123 119 124 129 131 13...  PrivateTest
35861        6  233 232 208 188 194 179 177 167 157 180 185 19...  PrivateTest
35862        2  73 54 63 76 82 71 67 69 73 72 92 98 117 119 14...  PrivateTest
35863        5  196 196 197 197 198 198 198 196 176 148 122 10...  PrivateTest
35864        4  68 59 65 78 118 131 137 141 142 135 135 137 13...  PrivateTest
35865        3  102 109 109 106 104 107 112 109 116 119 117 12...  PrivateTest
35866        6  87 82 59 61 72 102 143 130 90 95 143 173 146 1...  PrivateTest
35867        3  198 198 197 196 196 197 196 196 196 195 196 18...  PrivateTest
35868        2  204 209 215 218 214 214 214 217 205 175 170 16...  PrivateTest
35869        3  217 220 222 223 223 224 225 223 223 225 223 22...  PrivateTest
35870        2  6 8 4 5 30 48 61 70 76 79 98 117 130 137 143 1...  PrivateTest
35871        6  112 102 98 89 98 133 164 185 180 179 185 169 1...  PrivateTest
35872        5  131 159 90 59 10 0 1 1 1 0 1 1 0 0 2 2 5 7 9 1...  PrivateTest
35873        4  54 57 77 122 121 76 73 80 58 22 26 27 35 41 66...  PrivateTest
35874        5  43 43 51 73 94 97 102 95 99 107 126 144 154 17...  PrivateTest
35875        5  248 251 239 144 102 95 82 77 91 138 153 145 14...  PrivateTest
35876        6  29 29 27 31 49 56 29 19 22 20 34 43 55 71 85 9...  PrivateTest
35877        6  139 143 145 154 159 168 176 181 190 191 195 19...  PrivateTest
35878        3  0 39 81 80 104 97 51 64 68 46 41 67 53 68 70 5...  PrivateTest
35879        2  0 0 6 16 19 31 47 18 26 19 17 8 15 3 4 2 14 20...  PrivateTest
35880        2  164 172 175 171 172 173 178 181 188 192 197 20...  PrivateTest
35881        0  181 177 176 156 178 144 136 132 122 107 131 16...  PrivateTest
35882        6  50 36 17 22 23 29 33 39 34 37 37 37 39 43 48 5...  PrivateTest
35883        3  178 174 172 173 181 188 191 194 196 199 200 20...  PrivateTest
35884        0  17 17 16 23 28 22 19 17 25 26 20 24 31 19 27 9...  PrivateTest
35885        3  30 28 28 29 31 30 42 68 79 81 77 67 67 71 63 6...  PrivateTest
35886        2  19 13 14 12 13 16 21 33 50 57 71 84 97 108 122...  PrivateTest

[35887 rows x 3 columns]

In [4]:
prep.load_data('fer2013.csv', name='alldata')['Usage'].unique().tolist()

['Training', 'PublicTest', 'PrivateTest']

In [5]:
pixels=prep.get(name='alldata')['pixels']

In [6]:
pixels = pixels.str.split(' ', n=48*48, expand = True)

In [7]:
pixels

,0,1,2,3,4,5,6,7,8,9,...,2294,2295,2296,2297,2298,2299,2300,2301,2302,2303
0,70,80,82,72,58,58,60,63,54,58,...,159,182,183,136,106,116,95,106,109,82
1,151,150,147,155,148,133,111,140,170,174,...,105,108,95,108,102,67,171,193,183,184
2,231,212,156,164,174,138,161,173,182,200,...,104,138,152,122,114,101,97,88,110,152
3,24,32,36,30,32,23,19,20,30,41,...,174,126,132,132,133,136,139,142,143,142
4,4,0,0,0,0,0,0,0,0,0,...,12,34,31,31,31,27,31,30,29,30
5,55,55,55,55,55,54,60,68,54,85,...,90,83,77,53,37,34,30,34,30,57
6,20,17,19,21,25,38,42,42,46,54,...,29,36,68,91,85,93,97,99,107,118
7,77,78,79,79,78,75,60,55,47,48,...,126,124,139,150,179,180,175,125,67,68
8,85,84,90,121,101,102,133,153,153,169,...,132,151,111,106,102,99,89,58,73,84
9,255,254,255,254,254,179,122,107,95,124,...,160,176,188,251,252,253,253,254,255,255
10,30,24,21,23,25,25,49,67,84,103,...,92,106,111,148,137,176,174,172,173,173
11,39,75,78,58,58,45,49,48,103,156,...,106,85,79,75,75,75,82,84,83,87
12,219,213,206,202,209,217,216,215,219,218,...,13,16,17,17,19,13,0,0,0,0
13,148,144,130,129,119,122,129,131,139,153,...,113,114,112,111,112,112,112,112,111,111
14,4,2,13,41,56,62,67,87,95,62,...,59,66,80,74,69,99,28,3,7,12
15,107,107,109,109,109,109,110,101,123,140,...,94,59,78,83,82,83,82,83,84,106
16,14,14,18,28,27,22,21,30,42,61,...,178,166,151,140,100,49,4,9,10,10
17,255,255,255,255,255,255,255,255,255,255,...,94,21,22,51,71,80,82,79,79,83
18,134,124,167,180,197,194,203,210,204,203,...,75,89,97,103,95,80,61,34,28,139
19,219,192,179,148,208,254,192,98,121,103,...,43,122,110,29,24,28,32,57,39,40
20,1,1,1,1,1,1,1,1,1,1,...,231,241,239,236,226,237,226,213,211,215
21,174,51,37,37,38,41,22,25,22,24,...,19,14,11,12,22,23,12,7,11,16
22,123,125,124,142,209,226,234,236,231,232,...,105,103,116,111,105,105,103,97,91,89
23,8,9,14,21,26,32,37,46,52,62,...,77,74,75,74,80,91,101,103,122,130
24,252,250,246,229,182,140,98,72,53,44,...,58,85,118,120,115,110,115,62,47,30
25,224,227,219,217,215,210,187,177,189,200,...,210,205,175,150,170,205,118,17,75,166
26,162,200,187,180,197,198,196,192,176,152,...,116,89,82,81,92,115,91,113,113,94
27,236,230,225,226,228,209,199,193,196,211,...,186,192,190,186,171,144,144,152,155,173
28,210,210,210,210,211,207,147,103,68,60,...,136,120,99,100,95,75,77,85,82,144
29,50,44,74,141,187,187,169,113,80,128,...,124,81,38,34,42,39,32,35,35,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35857,253,255,229,150,89,61,54,60,55,49,...,227,255,254,255,255,255,255,255,255,255
35858,11,11,11,13,20,27,38,41,38,34,...,6,6,7,7,7,5,16,30,32,29
35859,11,13,16,27,24,26,89,161,190,197,...,219,221,218,206,200,209,216,210,210,217
35860,27,42,62,91,112,118,122,123,119,124,...,211,206,206,218,235,226,182,182,215,226
35861,233,232,208,188,194,179,177,167,157,180,...,154,160,170,172,178,172,180,186,177,190
35862,73,54,63,76,82,71,67,69,73,72,...,60,54,45,47,42,38,39,34,33,33
35863,196,196,197,197,198,198,198,196,176,148,...,142,142,140,138,83,15,11,8,9,19
35864,68,59,65,78,118,131,137,141,142,135,...,69,70,72,66,63,65,59,51,50,45
35865,102,109,109,106,104,107,112,109,116,119,...,42,19,26,51,37,24,28,31,39,33
35866,87,82,59,61,72,102,143,130,90,95,...,90,77,74,68,60,52,46,37,23,20
35867,198,198,197,196,196,197,196,196,196,195,...,123,190,200,197,195,195,188,179,174,173
35868,204,209,215,218,214,214,214,217,205,175,...,146,166,158,166,196,216,210,180,174,178
35869,217,220,222,223,223,224,225,223,223,225,...,125,119,114,111,118,116,111,106,88,45
35870,6,8,4,5,30,48,61,70,76,79,...,137,146,136,123,116,113,106,156,209,190
35871,112,102,98,89,98,133,164,185,180,179,...,17,15,15,16,13,16,18,16,22,18
35872,131,159,90,59,10,0,1,1,1,0,...,54,74,207,232,158,195,242,255,255,255
35873,54,57,77,122,121,76,73,80,58,22,...,126,58,3,38,11,31,36,23,25,33
35874,43,43,51,73,94,97,102,95,99,107,...,67,15,21,18,17,18,17,19,20,23
35875,248,251,239,144,102,95,82,77,91,138,...,164,167,152,154,163,153,179,231,238,237
35876,29,29,27,31,49,56,29,19,22,20,...,21,22,19,17,30,29,13,15,26,60
35877,139,143,145,154,159,168,176,181,190,191,...,104,108,110,109,103,100,95,99,190,220
35878,0,39,81,80,104,97,51,64,68,46,...,202,253,244,238,226,222,226,191,102,102
35879,0,0,6,16,19,31,47,18,26,19,...,216,226,224,228,235,237,240,238,191,123
35880,164,172,175,171,172,173,178,181,188,192,...,217,215,214,216,218,217,222,223,227,231
35881,181,177,176,156,178,144,136,132,122,107,...,133,155,156,107,31,53,74,60,28,55
35882,50,36,17,22,23,29,33,39,34,37,...,216,215,216,217,221,222,220,223,221,216
35883,178,174,172,173,181,188,191,194,196,199,...,147,141,136,118,66,7,0,0,0,0
35884,17,17,16,23,28,22,19,17,25,26,...,190,179,193,193,194,170,148,154,133,113
35885,30,28,28,29,31,30,42,68,79,81,...,30,27,27,26,28,35,35,35,30,28
35886,19,13,14,12,13,16,21,33,50,57,...,224,217,209,195,151,99,146,189,199,201

In [8]:
pixels_norm = pixels.applymap(lambda x: float(x)/255)
pixels_norm.tail()

,0,1,2,3,4,5,6,7,8,9,...,2294,2295,2296,2297,2298,2299,2300,2301,2302,2303
35882,0.196078,0.141176,0.066667,0.086275,0.090196,0.113725,0.129412,0.152941,0.133333,0.145098,...,0.847059,0.843137,0.847059,0.850980,0.866667,0.870588,0.862745,0.874510,0.866667,0.847059
35883,0.698039,0.682353,0.674510,0.678431,0.709804,0.737255,0.749020,0.760784,0.768627,0.780392,...,0.576471,0.552941,0.533333,0.462745,0.258824,0.027451,0.000000,0.000000,0.000000,0.000000
35884,0.066667,0.066667,0.062745,0.090196,0.109804,0.086275,0.074510,0.066667,0.098039,0.101961,...,0.745098,0.701961,0.756863,0.756863,0.760784,0.666667,0.580392,0.603922,0.521569,0.443137
35885,0.117647,0.109804,0.109804,0.113725,0.121569,0.117647,0.164706,0.266667,0.309804,0.317647,...,0.117647,0.105882,0.105882,0.101961,0.109804,0.137255,0.137255,0.137255,0.117647,0.109804
35886,0.074510,0.050980,0.054902,0.047059,0.050980,0.062745,0.082353,0.129412,0.196078,0.223529,...,0.878431,0.850980,0.819608,0.764706,0.592157,0.388235,0.572549,0.741176,0.780392,0.788235

In [9]:
data = pixels.join(prep.load_data('fer2013.csv', name='alldata')['emotion']).join(prep.load_data('fer2013.csv', name='alldata')['Usage'])

In [10]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,2296,2297,2298,2299,2300,2301,2302,2303,emotion,Usage
0,70,80,82,72,58,58,60,63,54,58,...,183,136,106,116,95,106,109,82,0,Training
1,151,150,147,155,148,133,111,140,170,174,...,95,108,102,67,171,193,183,184,0,Training
2,231,212,156,164,174,138,161,173,182,200,...,152,122,114,101,97,88,110,152,2,Training
3,24,32,36,30,32,23,19,20,30,41,...,132,132,133,136,139,142,143,142,4,Training
4,4,0,0,0,0,0,0,0,0,0,...,31,31,31,27,31,30,29,30,6,Training

In [11]:
data_norm = pixels_norm.join(prep.load_data('fer2013.csv', name='alldata')['emotion']).join(prep.load_data('fer2013.csv', name='alldata')['Usage'])
data_norm.head()

,0,1,2,3,4,5,6,7,8,9,...,2296,2297,2298,2299,2300,2301,2302,2303,emotion,Usage
0,0.274510,0.313725,0.321569,0.282353,0.227451,0.227451,0.235294,0.247059,0.211765,0.227451,...,0.717647,0.533333,0.415686,0.454902,0.372549,0.415686,0.427451,0.321569,0,Training
1,0.592157,0.588235,0.576471,0.607843,0.580392,0.521569,0.435294,0.549020,0.666667,0.682353,...,0.372549,0.423529,0.400000,0.262745,0.670588,0.756863,0.717647,0.721569,0,Training
2,0.905882,0.831373,0.611765,0.643137,0.682353,0.541176,0.631373,0.678431,0.713725,0.784314,...,0.596078,0.478431,0.447059,0.396078,0.380392,0.345098,0.431373,0.596078,2,Training
3,0.094118,0.125490,0.141176,0.117647,0.125490,0.090196,0.074510,0.078431,0.117647,0.160784,...,0.517647,0.517647,0.521569,0.533333,0.545098,0.556863,0.560784,0.556863,4,Training
4,0.015686,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.121569,0.121569,0.121569,0.105882,0.121569,0.117647,0.113725,0.117647,6,Training

In [12]:
prep.set(name='cleaned', value=data)
prep.save(name='cleaned')

In [13]:
usage_values = prep.get(name='cleaned')['Usage'].unique().tolist()
usage_values

['Training', 'PublicTest', 'PrivateTest']

In [14]:
train = prep.get(name='cleaned').loc[prep.get(name='cleaned')['Usage'] == 'Training']

In [15]:
train.tail()

,0,1,2,3,4,5,6,7,8,9,...,2296,2297,2298,2299,2300,2301,2302,2303,emotion,Usage
28704,84,85,85,85,85,85,85,85,86,86,...,35,36,40,27,125,231,215,200,2,Training
28705,114,112,113,113,111,111,112,113,115,113,...,107,120,141,144,132,129,182,222,0,Training
28706,74,81,87,89,95,100,98,93,105,120,...,211,209,200,195,192,188,187,187,4,Training
28707,222,227,203,90,86,90,84,77,94,87,...,141,145,137,139,136,136,136,134,0,Training
28708,195,199,205,206,205,203,206,209,208,210,...,67,34,6,7,3,6,15,38,4,Training

In [50]:
prep.set(name='train', value = train.drop(columns = ['Usage']))
prep.save(name='train')

In [16]:
train_norm = data_norm.loc[data_norm['Usage'] == 'Training']
train_norm.tail()

,0,1,2,3,4,5,6,7,8,9,...,2296,2297,2298,2299,2300,2301,2302,2303,emotion,Usage
28704,0.329412,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.337255,0.337255,...,0.137255,0.141176,0.156863,0.105882,0.490196,0.905882,0.843137,0.784314,2,Training
28705,0.447059,0.439216,0.443137,0.443137,0.435294,0.435294,0.439216,0.443137,0.450980,0.443137,...,0.419608,0.470588,0.552941,0.564706,0.517647,0.505882,0.713725,0.870588,0,Training
28706,0.290196,0.317647,0.341176,0.349020,0.372549,0.392157,0.384314,0.364706,0.411765,0.470588,...,0.827451,0.819608,0.784314,0.764706,0.752941,0.737255,0.733333,0.733333,4,Training
28707,0.870588,0.890196,0.796078,0.352941,0.337255,0.352941,0.329412,0.301961,0.368627,0.341176,...,0.552941,0.568627,0.537255,0.545098,0.533333,0.533333,0.533333,0.525490,0,Training
28708,0.764706,0.780392,0.803922,0.807843,0.803922,0.796078,0.807843,0.819608,0.815686,0.823529,...,0.262745,0.133333,0.023529,0.027451,0.011765,0.023529,0.058824,0.149020,4,Training

In [24]:
prep.set(name='train_norm', value = train_norm.drop(columns = ['Usage']))
prep.save(name='train_norm')

In [51]:
publicTest = prep.get(name='cleaned').loc[prep.get(name='cleaned')['Usage'] == 'PublicTest']

In [ ]:
prep.set(name='test_public', value = publicTest.drop(columns = ['Usage']))
prep.save(name='test_public')

In [25]:
publicTest_norm = data_norm.loc[data_norm['Usage'] == 'PublicTest']

In [33]:
prep.set(name='test_public_norm', value = publicTest_norm.drop(columns = ['Usage']))
prep.save(name='test_public_norm')

In [54]:
privateTest = prep.get(name='cleaned').loc[prep.get(name='cleaned')['Usage'] == 'PrivateTest']

In [55]:
prep.set(name='test_private', value = privateTest.drop(columns = ['Usage']))
prep.save(name='test_private')

In [26]:
privateTest_norm = data_norm.loc[data_norm['Usage'] == 'PrivateTest']

In [27]:
prep.set(name='test_private_norm', value = privateTest_norm.drop(columns = ['Usage']))
prep.save(name='test_private_norm')

In [28]:
#Create a reduced set of training images
import random

In [29]:
train_data = prep.load_data(filename='train_norm.csv', name='train')

In [30]:
train_data_reduced = train_data.sample(n=7000)

In [31]:
train_data_reduced.tail()

,0,1,2,3,4,5,6,7,8,9,...,2295,2296,2297,2298,2299,2300,2301,2302,2303,emotion
15031,0.050980,0.019608,0.003922,0.015686,0.023529,0.035294,0.027451,0.027451,0.023529,0.019608,...,0.650980,0.662745,0.690196,0.686275,0.678431,0.658824,0.588235,0.439216,0.380392,6
12654,0.529412,0.525490,0.466667,0.403922,0.439216,0.623529,0.752941,0.705882,0.600000,0.654902,...,0.325490,0.678431,0.835294,0.635294,0.117647,0.121569,0.266667,0.341176,0.454902,2
9566,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.984314,1.000000,0.709804,...,0.611765,0.607843,0.611765,0.580392,0.588235,0.647059,0.749020,0.847059,0.862745,0
16168,1.000000,1.000000,0.984314,0.619608,0.219608,0.243137,0.172549,0.160784,0.176471,0.176471,...,0.752941,0.521569,0.431373,1.000000,0.968627,0.964706,0.980392,0.984314,0.980392,2
24165,0.729412,0.776471,0.780392,0.713725,0.658824,0.729412,0.780392,0.796078,0.811765,0.815686,...,0.752941,0.749020,0.741176,0.662745,0.396078,0.549020,0.760784,0.423529,0.584314,2

In [32]:
prep.set(name='train_reduced_norm', value = train_data_reduced)
prep.save(name='train_reduced_norm')

# I have normalized, values are between 0.0 - 1.0 but  I want them between -1.0 - 1.0

In [24]:
train_norm_np = train_norm.drop(columns = ['emotion', 'Usage']).values
train_norm_np -= 0.5
train_norm_np *= 2

In [25]:
train_norm_np

array([[-0.45098039, -0.37254902, -0.35686275, ..., -0.16862745,
        -0.14509804, -0.35686275],
       [ 0.18431373,  0.17647059,  0.15294118, ...,  0.51372549,
         0.43529412,  0.44313725],
       [ 0.81176471,  0.6627451 ,  0.22352941, ..., -0.30980392,
        -0.1372549 ,  0.19215686],
       ...,
       [-0.41960784, -0.36470588, -0.31764706, ...,  0.4745098 ,
         0.46666667,  0.46666667],
       [ 0.74117647,  0.78039216,  0.59215686, ...,  0.06666667,
         0.06666667,  0.05098039],
       [ 0.52941176,  0.56078431,  0.60784314, ..., -0.95294118,
        -0.88235294, -0.70196078]])

In [29]:
import pandas as pd

train_standarized = pd.DataFrame(train_norm_np)
train_standarized.head()

,0,1,2,3,4,5,6,7,8,9,...,2294,2295,2296,2297,2298,2299,2300,2301,2302,2303
0,-0.450980,-0.372549,-0.356863,-0.435294,-0.545098,-0.545098,-0.529412,-0.505882,-0.576471,-0.545098,...,0.247059,0.427451,0.435294,0.066667,-0.168627,-0.090196,-0.254902,-0.168627,-0.145098,-0.356863
1,0.184314,0.176471,0.152941,0.215686,0.160784,0.043137,-0.129412,0.098039,0.333333,0.364706,...,-0.176471,-0.152941,-0.254902,-0.152941,-0.200000,-0.474510,0.341176,0.513725,0.435294,0.443137
2,0.811765,0.662745,0.223529,0.286275,0.364706,0.082353,0.262745,0.356863,0.427451,0.568627,...,-0.184314,0.082353,0.192157,-0.043137,-0.105882,-0.207843,-0.239216,-0.309804,-0.137255,0.192157
3,-0.811765,-0.749020,-0.717647,-0.764706,-0.749020,-0.819608,-0.850980,-0.843137,-0.764706,-0.678431,...,0.364706,-0.011765,0.035294,0.035294,0.043137,0.066667,0.090196,0.113725,0.121569,0.113725
4,-0.968627,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-0.905882,-0.733333,-0.756863,-0.756863,-0.756863,-0.788235,-0.756863,-0.764706,-0.772549,-0.764706

In [30]:
train_standarized = train_standarized.join(train_norm['emotion'])
train_standarized.head()

,0,1,2,3,4,5,6,7,8,9,...,2295,2296,2297,2298,2299,2300,2301,2302,2303,emotion
0,-0.450980,-0.372549,-0.356863,-0.435294,-0.545098,-0.545098,-0.529412,-0.505882,-0.576471,-0.545098,...,0.427451,0.435294,0.066667,-0.168627,-0.090196,-0.254902,-0.168627,-0.145098,-0.356863,0
1,0.184314,0.176471,0.152941,0.215686,0.160784,0.043137,-0.129412,0.098039,0.333333,0.364706,...,-0.152941,-0.254902,-0.152941,-0.200000,-0.474510,0.341176,0.513725,0.435294,0.443137,0
2,0.811765,0.662745,0.223529,0.286275,0.364706,0.082353,0.262745,0.356863,0.427451,0.568627,...,0.082353,0.192157,-0.043137,-0.105882,-0.207843,-0.239216,-0.309804,-0.137255,0.192157,2
3,-0.811765,-0.749020,-0.717647,-0.764706,-0.749020,-0.819608,-0.850980,-0.843137,-0.764706,-0.678431,...,-0.011765,0.035294,0.035294,0.043137,0.066667,0.090196,0.113725,0.121569,0.113725,4
4,-0.968627,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-0.733333,-0.756863,-0.756863,-0.756863,-0.788235,-0.756863,-0.764706,-0.772549,-0.764706,6